// date localization for locale 'es'
// generated by Jörn Zaefferer using Java's java.util.SimpleDateFormat
Date.dayNames = ['domingo', 'lunes', 'martes', 'mi�rcoles', 'jueves', 'viernes', 's�bado'];
Date.abbrDayNames = ['dom', 'lun', 'mar', 'mi�', 'jue', 'vie', 's�b'];
Date.monthNames = ['enero', 'febrero', 'marzo', 'abril', 'mayo', 'junio', 'julio', 'agosto', 'septiembre', 'octubre', 'noviembre', 'diciembre'];
Date.abbrMonthNames = ['ene', 'feb', 'mar', 'abr', 'may', 'jun', 'jul', 'ago', 'sep', 'oct', 'nov', 'dic'];
