// date localization for locale 'id'
// generated by mirzalazuardi (twitter : @mirzalazuardi)
Date.dayNames = ['minggu', 'senin', 'selasa', 'rabu', 'kamis', 'jumat', 'sabtu'];
Date.abbrDayNames = ['mgg.', 'sen.', 'sel.', 'rab.', 'kam.', 'jum.', 'sab.'];
Date.monthNames = ['januari', 'februari', 'maret', 'april', 'mei', 'juni', 'juli', 'agustus', 'september', 'oktober', 'november', 'desember'];
Date.abbrMonthNames = ['jan.', 'feb.', 'mar', 'apr.', 'mei', 'jun', 'jul.', 'agust', 'sept.', 'okt.', 'nov.', 'des.'];
