// date localization for locale 'da'
// generated by Jørgen Orehøj Erichsen | www.erichsen.net
Date.dayNames = ['Søndag', 'Mandag', 'Tirsdag', 'Onsdag', 'Torsdag', 'Fredag', 'Lørdag'];
Date.abbrDayNames = ['Sø', 'Ma', 'Ti', 'On', 'To', 'Fr', 'Lø'];
Date.monthNames = ['Januar', 'Februar', 'Marts', 'April', 'Maj', 'Juni', 'Juli', 'August', 'September', 'Oktober', 'November', 'December'];
Date.abbrMonthNames = ['Jan', 'Feb', 'Mar', 'Apr', 'Maj', 'Jun', 'Jul', 'Aug', 'Sep', 'Okt', 'Nov', 'Dec'];