// date localization for locale 'se'
// generated by Gabriel Svennerberg | www.svennerberg.com
Date.dayNames = ['Söndag', 'Måndag', 'Tisdag', 'Onsdag', 'Torsdag', 'Fredag', 'Lördag'];
Date.abbrDayNames = ['Sö', 'Må', 'Ti', 'On', 'To', 'Fr', 'Lö'];
Date.monthNames = ['Januari', 'Februari', 'Mars', 'April', 'Maj', 'Juni', 'Juli', 'Augusti', 'September', 'Oktober', 'November', 'December'];
Date.abbrMonthNames = ['Jan', 'Feb', 'Mar', 'Apr', 'Maj', 'Jun', 'Jul', 'Aug', 'Sep', 'Okt', 'Nov', 'Dec'];