// date localization for locale 'tr'
// generated by Bora UNAL - bbunal@gmail.com
Date.dayNames = ['Pazar', 'Pazartesi', 'Salı', 'Çarşamba', 'Perşembe', 'Cuma', 'Cumartesi'];
Date.abbrDayNames = ['Paz', 'Pzt', 'Sal', 'Çarş', 'Perş', 'Cum', 'Cmt'];
Date.monthNames = ['Ocak', 'Şubat', 'Mart', 'Nisan', 'Mayıs', 'Haziran', 'Temmuz', 'Ağustos', 'Eylül', 'Ekim', 'Kasım', 'Aralık'];
Date.abbrMonthNames = ['Oca', 'Şub', 'Mar', 'Nis', 'May', 'Haz', 'Tem', 'Ağu', 'Eyl', 'Eki', 'Kas', 'Ara']; 