// date localization for locale 'no'
// generated by Aslak Johannessen | http://github.com/aslakjo

Date.dayNames = ['Søndag', 'Mandag', 'Tirsdag', 'Onsdag', 'Torsdag', 'Fredag', 'Lørdag'];
Date.abbrDayNames = ['Søn', 'Man', 'Tirs', 'Ons', 'Tors', 'Fre', 'Lør'];
Date.monthNames = ['Januar', 'Februar', 'Mars', 'April', 'Mai', 'Juni', 'Juli', 'August', 'September', 'Oktober', 'November', 'Desember'];
Date.abbrMonthNames = ['Jan', 'Feb', 'Mar', 'Apr', 'Mai', 'Jun', 'Jul', 'Aug', 'Sep', 'Okt', 'Nov', 'Des'];
Date.firstDayOfWeek = 1;
Date.format = 'dd/mm - yyyy';

$.dpText = {
    TEXT_PREV_YEAR		:	'Forrige år',
    TEXT_PREV_MONTH		:	'Forrige måned',
    TEXT_NEXT_YEAR		:	'Neste år',
    TEXT_NEXT_MONTH		:	'Neste måned',
    TEXT_CLOSE			:	'Lukk',
    TEXT_CHOOSE_DATE	:	'Velg dato',
    HEADER_FORMAT       :	'mmmm yyyy'
}
