// date localization for locale 'it'
// generated by Jörn Zaefferer using Java's java.util.SimpleDateFormat
Date.dayNames = ['domenica', 'lunedì', 'martedì', 'mercoledì', 'giovedì', 'venerdì', 'sabato'];
Date.abbrDayNames = ['dom', 'lun', 'mar', 'mer', 'gio', 'ven', 'sab'];
Date.monthNames = ['gennaio', 'febbraio', 'marzo', 'aprile', 'maggio', 'giugno', 'luglio', 'agosto', 'settembre', 'ottobre', 'novembre', 'dicembre'];
Date.abbrMonthNames = ['gen', 'feb', 'mar', 'apr', 'mag', 'giu', 'lug', 'ago', 'set', 'ott', 'nov', 'dic'];
